### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by baj12** [HCBravoLab/scTreeViz#4]
Hi, 
found your package via Twitter and was intrigued.

But I cannot test, because I cannot install:

```

> BiocManager::install("HCBravoLab/TreeViz")
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
Installing github package(s) 'HCBravoLab/TreeViz'
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo HCBravoLab/TreeViz@HEAD
✓  checking for file ‘/private/var/folders/d_/g1jsd9v96mvc9n0ds29v7m8m0000gn/T/RtmpEdbLNg/remotesf8de1a247e7/HCBravoLab-TreeViz-ca113fd/DESCRIPTION’ ...
─  preparing ‘TreeViz’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘TreeViz_0.1.0.tar.gz’
   
* installing *source* package ‘TreeViz’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Warning: replacing previous import 'SummarizedExperiment::shift' by 'data.table::shift' when loading 'TreeViz'
Warning: replacing previous import 'data.table::last' by 'dplyr::last' when loading 'TreeViz'
Warning: replacing previous import 'data.table::first' by 'dplyr::first' when loading 'TreeViz'
Warning: replacing previous import 'data.table::between' by 'dplyr::between' when loading 'TreeViz'
Warning: replacing previous import 'S4Vectors::merge' by 'git2r::merge' when loading 'epivizrStandalone'
Warning: replacing previous import 'S4Vectors::head' by 'git2r::head' when loading 'epivizrStandalone'
Warning: replacing previous import 'S4Vectors::as.data.frame' by 'git2r::as.data.frame' when loading 'epivizrStandalone'
Warning: replacing previous import 'dplyr::union' by 'igraph::union' when loading 'TreeViz'
Warning: replacing previous import 'dplyr::as_data_frame' by 'igraph::as_data_frame' when loading 'TreeViz'
Warning: replacing previous import 'dplyr::groups' by 'igraph::groups' when loading 'TreeViz'
Warning: replacing previous import 'igraph::normalize' by 'scater::normalize' when loading 'TreeViz'
Warning: replacing previous import 'igraph::groups' by 'tidygraph::groups' when loading 'TreeViz'
Error: class "SparseEpivizMeasurement" is not exported by 'namespace:epivizrData'
Execution halted
ERROR: lazy loading failed for package ‘TreeViz’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/TreeViz’
Error: Failed to install 'TreeViz' from GitHub:
  (converted from warning) installation of package ‘/var/folders/d_/g1jsd9v96mvc9n0ds29v7m8m0000gn/T//RtmpEdbLNg/filef8de59610b84/TreeViz_0.1.0.tar.gz’ had non-zero exit status
> 
```

```

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] prettyunits_1.1.1   ps_1.4.0            fansi_0.4.1         withr_2.3.0         rprojroot_1.3-2     crayon_1.3.4        assertthat_0.2.1   
 [8] R6_2.5.0            backports_1.2.0     cli_2.1.0           curl_4.3            remotes_2.2.0       rstudioapi_0.11     callr_3.5.1        
[15] tools_4.0.3         glue_1.4.2          yaml_2.2.1          compiler_4.0.3      processx_3.4.4      pkgbuild_1.1.0      BiocManager_1.30.10
> 
```

**Comment by jkanche** [comment]
Hi @baj12 

Thanks for trying it out! The package currently requires installing the `SparseMeasurements` branch of `epivizrData`. Install this either through `bioc` or `devtools`. we plan to push it to bioc release/devel soon

```
BiocManager::install("epiviz/epivizrData@SparseMeasurements")
```

Let me know if you continue to have issues.

**Comment by baj12** [comment]
SC3 is missing in the description file and necessary for the vignette

**Comment by jkanche** [comment]
Thank you @baj12 for testing it out!  I made a couple of more fixes wrt installation.

There's a new vignette walking through some fo the features of the app using the pbmc_3k dataset. 

https://hcbravolab.github.io/TreeViz/Explore-PBMC.html

let us know if you have any feedback or suggestions!

**Comment by jkanche** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Vignette with pbmc_3k dataset](https://trello.com/c/ARxVmQhE/106-vignette-with-pbmc3k-dataset)

**Comment by baj12** [comment]
Sorry, but I am still running into an installation problem:

```
> BiocManager::install("HCBravoLab/TreeViz")
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
Installing github package(s) 'HCBravoLab/TreeViz'
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo HCBravoLab/TreeViz@HEAD
✓  checking for file ‘/private/var/folders/d_/g1jsd9v96mvc9n0ds29v7m8m0000gn/T/RtmpFC58rJ/remotes5d851540dc2/HCBravoLab-TreeViz-d6b33c5/DESCRIPTION’ ...
─  preparing ‘TreeViz’: (347ms)
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘TreeViz/data/PBMC3k_TreeViz.RData’
─  building ‘TreeViz_0.1.0.tar.gz’
   
* installing *source* package ‘TreeViz’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Warning: replacing previous import 'SummarizedExperiment::shift' by 'data.table::shift' when loading 'TreeViz'
Warning: replacing previous import 'data.table::last' by 'dplyr::last' when loading 'TreeViz'
Warning: replacing previous import 'data.table::first' by 'dplyr::first' when loading 'TreeViz'
Warning: replacing previous import 'data.table::between' by 'dplyr::between' when loading 'TreeViz'
Warning: replacing previous import 'S4Vectors::merge' by 'git2r::merge' when loading 'epivizrStandalone'
Warning: replacing previous import 'S4Vectors::head' by 'git2r::head' when loading 'epivizrStandalone'
Warning: replacing previous import 'S4Vectors::as.data.frame' by 'git2r::as.data.frame' when loading 'epivizrStandalone'
Warning: replacing previous import 'dplyr::union' by 'igraph::union' when loading 'TreeViz'
Warning: replacing previous import 'dplyr::as_data_frame' by 'igraph::as_data_frame' when loading 'TreeViz'
Warning: replacing previous import 'dplyr::groups' by 'igraph::groups' when loading 'TreeViz'
Warning: replacing previous import 'igraph::normalize' by 'scater::normalize' when loading 'TreeViz'
Warning: replacing previous import 'igraph::groups' by 'tidygraph::groups' when loading 'TreeViz'
Error: class "SparseEpivizMeasurement" is not exported by 'namespace:epivizrData'
Execution halted
ERROR: lazy loading failed for package ‘TreeViz’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/TreeViz’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/TreeViz’
Error: Failed to install 'TreeViz' from GitHub:
  (converted from warning) installation of package '/var/folders/d_/g1jsd9v96mvc9n0ds29v7m8m0000gn/T//RtmpFC58rJ/file5d865536544/TreeViz_0.1.0.tar.gz' had non-zero exit status
> 
> 
```

**Comment by jkanche** [comment]
Hi @baj12  

We merged the `sparseMeasurement` branch of epivizrData with the master branch so

```
BiocManager::install(c("epiviz/epivizrData", "HCBravoLab/TreeViz"))
```

can you post your `sessionInfo` ?

**Comment by baj12** [comment]
It seems the installation worked, but there is still a problem loading the library:

```> library(TreeViz)
Loading required package: epivizr
Loading required package: SummarizedExperiment
Loading required package: MatrixGenerics
Loading required package: matrixStats

Attaching package: 'matrixStats'

The following objects are masked from 'package:Biobase':

    anyMissing, rowMedians


Attaching package: 'MatrixGenerics'

The following objects are masked from 'package:matrixStats':

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse, colCounts, colCummaxs,
    colCummins, colCumprods, colCumsums, colDiffs, colIQRDiffs, colIQRs, colLogSumExps,
    colMadDiffs, colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats, colProds,
    colQuantiles, colRanges, colRanks, colSdDiffs, colSds, colSums2, colTabulates,
    colVarDiffs, colVars, colWeightedMads, colWeightedMeans, colWeightedMedians,
    colWeightedSds, colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods, rowCumsums, rowDiffs,
    rowIQRDiffs, rowIQRs, rowLogSumExps, rowMadDiffs, rowMads, rowMaxs, rowMeans2,
    rowMedians, rowMins, rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars, rowWeightedMads,
    rowWeightedMeans, rowWeightedMedians, rowWeightedSds, rowWeightedVars

The following object is masked from 'package:Biobase':

    rowMedians

Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: S4Vectors

Attaching package: 'S4Vectors'

The following object is masked from 'package:base':

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Error: package or namespace load failed for 'TreeViz':
 class "SparseEpivizMeasurement" is not exported by 'namespace:epivizrData'
In addition: There were 12 warnings (use warnings() to see them)
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] SummarizedExperiment_1.20.0 GenomicRanges_1.42.0        GenomeInfoDb_1.26.1        
 [4] IRanges_2.24.0              S4Vectors_0.28.0            MatrixGenerics_1.2.0       
 [7] matrixStats_0.57.0          epivizr_2.20.0              synchronicity_1.3.5        
[10] bigmemory_4.5.36            Biobase_2.50.0              BiocGenerics_0.36.0        

loaded via a namespace (and not attached):
  [1] shinydashboard_0.7.1        tidyselect_1.1.0            heatmaply_1.1.1            
  [4] RSQLite_2.2.1               AnnotationDbi_1.52.0        htmlwidgets_1.5.2          
  [7] grid_4.0.3                  TSP_1.1-10                  BiocParallel_1.24.1        
 [10] Rtsne_0.15                  munsell_0.5.0               codetools_0.2-18           
 [13] statmod_1.4.35              scran_1.18.1                DT_0.16                    
 [16] withr_2.3.0                 colorspace_2.0-0            Category_2.56.0            
 [19] OrganismDbi_1.32.0          pcaExplorer_2.16.0          knitr_1.30                 
 [22] uuid_0.1-4                  rstudioapi_0.13             SingleCellExperiment_1.12.0
 [25] NMF_0.23.0                  git2r_0.27.1                GenomeInfoDbData_1.2.4     
 [28] polyclip_1.10-0             topGO_2.42.0                farver_2.0.3               
 [31] bit64_4.0.5                 pheatmap_1.0.12             rprojroot_2.0.2            
 [34] vctrs_0.3.5                 generics_0.1.0              xfun_0.19                  
 [37] BiocFileCache_1.14.0        R6_2.5.0                    doParallel_1.0.16          
 [40] ggbeeswarm_0.6.0            graphlayouts_0.7.1          rsvd_1.0.3                 
 [43] seriation_1.2-9             locfit_1.5-9.4              AnnotationFilter_1.14.0    
 [46] bitops_1.0-6                shinyAce_0.4.1              DelayedArray_0.16.0        
 [49] assertthat_0.2.1            promises_1.1.1              scales_1.1.1               
 [52] ggraph_2.0.4                beeswarm_0.2.3              gtable_0.3.0               
 [55] beachmat_2.6.2              processx_3.4.5              tidygraph_1.2.0            
 [58] ensembldb_2.14.0            rlang_0.4.9                 genefilter_1.72.0          
 [61] splines_4.0.3               rtracklayer_1.50.0          lazyeval_0.2.2             
 [64] epivizrData_1.18.0          shinyjqui_0.3.3             shinyBS_0.61               
 [67] BiocManager_1.30.10         yaml_2.2.1                  reshape2_1.4.4             
 [70] GenomicFeatures_1.42.1      threejs_0.3.3               crosstalk_1.1.0.1          
 [73] httpuv_1.5.4                RBGL_1.66.0                 tools_4.0.3                
 [76] gridBase_0.4-7              ggplot2_3.3.2               ellipsis_0.3.1             
 [79] gplots_3.1.1                RColorBrewer_1.1-2          clustree_0.4.3             
 [82] Rcpp_1.0.5                  plyr_1.8.6                  sparseMatrixStats_1.2.0    
 [85] base64enc_0.1-3             progress_1.2.2              zlibbioc_1.36.0            
 [88] purrr_0.3.4                 RCurl_1.98-1.2              ps_1.4.0                   
 [91] prettyunits_1.1.1           openssl_1.4.3               viridis_0.5.1              
 [94] epivizrStandalone_1.18.0    ggrepel_0.8.2               cluster_2.1.0              
 [97] magrittr_2.0.1              data.table_1.13.2           SparseM_1.78               
[100] ProtGenerics_1.22.0         hms_0.5.3                   mime_0.9                   
[103] evaluate_0.14               xtable_1.8-4                XML_3.99-0.5               
[106] gridExtra_2.3               scater_1.18.3               compiler_4.0.3             
[109] biomaRt_2.46.0              tibble_3.0.4                KernSmooth_2.23-18         
[112] crayon_1.3.4                htmltools_0.5.0             GOstats_2.56.0             
[115] later_1.1.0.1               tidyr_1.1.2                 geneplotter_1.68.0         
[118] DBI_1.1.0                   tweenr_1.0.1                dbplyr_2.0.0               
[121] MASS_7.3-53                 rappdirs_0.3.1              sys_3.4                    
[124] Matrix_1.2-18               epivizrServer_1.18.0        cli_2.2.0                  
[127] igraph_1.2.6                pkgconfig_2.0.3             bigmemory.sri_0.1.3        
[130] GenomicAlignments_1.26.0    registry_0.5-1              scuttle_1.0.3              
[133] plotly_4.9.2.1              xml2_1.3.2                  foreach_1.5.1              
[136] annotate_1.68.0             vipor_0.4.5                 dqrng_0.2.1                
[139] rngtools_1.5                pkgmaker_0.32.2             webshot_0.5.2              
[142] XVector_0.30.0              AnnotationForge_1.32.0      stringr_1.4.0              
[145] callr_3.5.1                 digest_0.6.27               graph_1.68.0               
[148] Biostrings_2.58.0           rmarkdown_2.5               edgeR_3.32.0               
[151] dendextend_1.14.0           DelayedMatrixStats_1.12.1   GSEABase_1.52.0            
[154] curl_4.3                    shiny_1.5.0                 Rsamtools_2.6.0            
[157] gtools_3.8.2                rjson_0.2.20                lifecycle_0.2.0            
[160] jsonlite_1.7.1              BiocNeighbors_1.8.1         viridisLite_0.3.0          
[163] askpass_1.1                 limma_3.46.0                fansi_0.4.1                
[166] pillar_1.4.7                lattice_0.20-41             fastmap_1.0.1              
[169] httr_1.4.2                  pkgbuild_1.1.0              survival_3.2-7             
[172] GO.db_3.12.1                glue_1.4.2                  remotes_2.2.0              
[175] UpSetR_1.4.0                iterators_1.0.13            bluster_1.0.0              
[178] bit_4.0.4                   Rgraphviz_2.34.0            ggforce_0.3.2              
[181] stringi_1.5.3               blob_1.2.1                  BiocSingular_1.6.0         
[184] DESeq2_1.30.0               caTools_1.18.0              memoise_1.1.0              
[187] dplyr_1.0.2                 irlba_2.3.3                
```

**Comment by jkanche** [comment]
Hi @baj12, I bumped the version on `epivizrData` 

Sorry for the trouble but can you rerun the command again ? 

`BiocManager::install(c("epiviz/epivizrData", "HCBravoLab/TreeViz"))`

**Comment by baj12** [comment]
After restarting R it loads. 
Thanks
Bernd

PS. Which license are you using?
